#defaults for page variables
getStartedClass: null
authenticationClass: null
hitLimitClass: null
getLiveTestClass: null
generateInviteLinkClass: null
getCandidateReportClass: null
liveApiClass: null
prerequisitesClass: null

baseurl: "shu111" 


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

